version: '3.8'
services:
  wordpress:
    build: .
    container_name: wordpress_app
    depends_on:
      - db
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress_db_user
      WORDPRESS_DB_PASSWORD: wordpress_db_pass
      WORDPRESS_DB_NAME: wordpress_db
  db:
    image: mariadb
    container_name: wordpress_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress_db_pass
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_db_user
      MYSQL_PASSWORD: wordpress_db_pass
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: